### ISSUE TITLE
VUE cannot be integgrated via "script source"

### ISSUE THREAD

**Issue by imdippel** [synqs/DjangoControlServer#1]
Imoirting VUE in the masterpage.html does not work

**Comment by imdippel** [comment]
I am calling the device.list.html with the function "IndexView" in the view.py of pd_monitor/. Integrating the javascript file "index.js" from "static" works just fine and basic js is rendered as expected. However neither putting in "<script src="https://to/vue/"></script>" at the "masterpage.html" nor in "device_list.html" does the trick....

**Comment by fretchen** [comment]
It does not feel like it is not working too me. At the beginning there are no devices saved. So `device_list` should be empty. Only once we have a device we should see something IMHO.

**Comment by imdippel** [comment]
I now realize that it is not too smart to upload every bit I am creating... So the current version was probably something I just typed down haphazardly and uploaded at my computer at home such that I am on the latest version when using my laptop at the Institute.... I will make a new approach and let you know, when it is ready for your testing
