### ISSUE TITLE
being able to open the index page

### ISSUE THREAD

**Issue by fretchen** [synqs/DjangoControlServer#4]
Should I be able to open the index page ? right now I get the attached error:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/8323674/123113024-82a75f80-d43e-11eb-9467-e676f3db4a0b.png">

**Comment by imdippel** [comment]
ahh about that...Happens sometimes. I usually just reload the website and then everything is fine. Will have a look at some point

**Comment by imdippel** [comment]
Added the favicon.ico icon django automatically looks for in the root directory. It sits now in `main/static/main/` and the corresponding path is set in the `urls.py`
